#!/usr/bin/env python
import urllib2
import sys

def main(url, data):
	r = urllib2.Request(url, data=data)
	u = urllib2.urlopen(r)
	print u.read()
	return u.read()

if __name__ == "__main__":
	main(sys.argv[1], sys.argv[2]) 
